language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - 14

addons:
  apt:
    packages:
      # Manually install Cypress dependency.
      - libgconf-2-4

cache:
  npm: true
  directories:
    # Cache folder with Cypress binary.
    - ~/.cache

script:
  - npm install
  - npm run format:check
  - npm run lint
  - npm run test

after_script: npx codecov@3

jobs:
  include:
    - stage: dev-build-deploy
      name: "Build Development Site and Deploy to GitHub Pages"
      os: linux
      node_js: "lts/*"
      script: npm run build:dev && npm run test:e2e && echo "Deploying to GitHub Pages..."
      if: branch = dev
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: dist/
        github-token: $GITHUB_API_KEY
        keep-history: true
        repo: kenchandev/dev.kenchandev.github.io
        target-branch: master
        on:
          branch: dev
    - stage: prod-build-deploy
      name: "Build Production Site and Deploy to GitHub Pages"
      os: linux
      node_js: "lts/*"
      script: npm run build:prod && npm run test:e2e && echo "Deploying to GitHub Pages..."
      if: branch = master
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: dist/
        github-token: $GITHUB_API_KEY
        keep-history: true
        repo: kenchandev/kenchandev.github.io
        target-branch: master
        on:
          branch: master
