language: node_js

os:
  - linux
  - osx

node_js:
  - "node"
  - "lts/*"
  - 10

script:
  - npm install
  - npm run format:check
  - npm run lint
  - npm run build:prod

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist/
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    repo: kenchandev/kenchandev.github.io
    branch: master
